default:
  x_y_step: 0.1
  zstep: -0.035
  n_hidden: 50
  hidden_state_size: 100
  n_steps: 1
  gamma: 0.9
  target_update_rate: 1000
  lr: 0.0003
  initial_temperature: 3.001
  min_train_steps_per_episode: 100
  pretrain_steps: 0
  batch_size: 15
  handcrafted_factor: 0.0
  stop_after_episode: 300
  learning_rule: double_q_learning
  model: MLP
  agent: MLPAgent


gridsearch:
    config1:
        learning_rule:
        - double_q_learning
        target_update_rate:
        - 500
        - 1000
        min_train_steps_per_episode:
        - 100
    config2:
        learning_rule:
        - double_expected_sarsa
        target_update_rate:
        - 500
        - 9999999
        min_train_steps_per_episode:
        - 100
